#!/bin/bash

command_not_found_handle () {
	if ! docker inspect --format '{{ .Author }}' "$1" >&/dev/null; then
		echo "$0: $1: command not found"
		return
	fi

	if docker inspect --format '{{ .Id }}' "$1" | grep -q "^$1" ;then
		echo "$0: $1: command not found"
		return
	fi

	DEVICES=
	for DEV in /dev/kvm /dev/ttyUSB* /dev/dri/* /dev/snd/*; do
		if [ -b "$DEV" ] || [ -c "$DEV" ]; then
			DEVICES="$DEVICES --device $DEV:$DEV"
		fi
	done

	VOLUMES=
	for VOL in /tmp/.X11-unix /run/user; do
		if [ -e "$VOL" ]; then
			VOLUMES="$VOLUMES --volume $VOL:$VOL"
		fi
	done

	DASHT=
	tty -s && DASHT=-t

	docker run $DASHT -i -u $(whoami) -w "$HOME" \
		$(env | cut -d= -f1 | awk '{print "-e", $1}') \
		$DOCKERFILES_RUN_FLAGS \
		$DEVICES \
		$VOLUMES \
		-v /etc/passwd:/etc/passwd:ro \
		-v /etc/group:/etc/group:ro \
		-v /etc/localtime:/etc/localtime:ro \
		-v /home:/home \
		"$@"
}